# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rodapp', '0002_auto_20170811_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null=True)),
                ('api_url', models.CharField(max_length=500, null=True)),
                ('api_key', models.CharField(max_length=45, null=True)),
                ('desc', models.CharField(max_length=500, null=True)),
                ('param', models.CharField(max_length=45, null=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('updated_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'algorithms',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('calculations', models.CharField(max_length=500, null=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('updated_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'features',
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('period', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=0, max_digits=2)),
                ('result', models.IntegerField()),
                ('actual', models.IntegerField()),
                ('created_date', models.DateTimeField(null=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodapp.Algorithm')),
                ('feature', models.ManyToManyField(db_table=b'xpredictionfeature', to='rodapp.Feature')),
            ],
            options={
                'db_table': 'predictions',
            },
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null=True)),
                ('url', models.CharField(max_length=500, null=True)),
                ('api_url', models.CharField(max_length=500, null=True)),
                ('api_key', models.CharField(max_length=45, null=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('updated_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'symbols',
            },
        ),
        migrations.AddField(
            model_name='prediction',
            name='symbol',
            field=models.ManyToManyField(db_table=b'xpredictionsymbol', to='rodapp.Symbol'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
